Use single quotes in install examples
pivotal-cf/docs-build-service pull request #271
Opened 2021-07-21 19:13 UTC by tylerphelan

- This ensures no interpolation of critical values

2021-07-21 19:18 UTC, dumez-k requested changes
We probably also want to change the quotes in `faq.html.md.erb` lines 124-126 and 147-152

2021-07-21 21:56 UTC, matthewmcnew approved these changes

2021-07-21 21:59 UTC, tylerphelan commented
@dumez-k 
> We probably also want to change the quotes in `faq.html.md.erb` lines 124-126 and 147-152

good call, fixed. although the variables actually need quotes in one of those examples 😂

2021-07-21 22:39 UTC, tomkennedy513 approved these changes

2021-07-22 13:38 UTC, dumez-k approved these changes
Looks great!

2021-07-27 15:15 UTC, merged