Add documentation for using carvel secret-gen-controller
pivotal-cf/docs-build-service pull request #288
Opened 2022-01-20 20:59 UTC by dumez-k

2022-01-20 21:14 UTC, tylerphelan commented on synced-secrets.html.md.erb
> +<p class='note'><strong>Note:</strong> As of TBS version 1.4 all secrets with the label "tbs-builder-secret-gen-placeholder-secret" will be deleted as this method of secret-syncing is deprecated. Ple
old label is `com.vmware.tanzu.buildservice.sync`

2022-01-20 21:15 UTC, tylerphelan commented on synced-secrets.html.md.erb
> +<p class='note'><strong>Note:</strong> As of TBS version 1.4 all secrets with the label "tbs-builder-secret-gen-placeholder-secret" will be deleted as this method of secret-syncing is deprecated. Ple
you also shouldn't need to set the new label: `com.vmware.tanzu.buildservice.placeholder`

2022-01-20 21:17 UTC, tylerphelan commented on synced-secrets.html.md.erb
> +To start synchronizing a secret to all namespaces with builds, use `kubectl` to create a docker-registry (Dockercfg or DockerConfigJson) secret in the `build-service` namespace with the following lab
I think the process is to create a SecretExport resource

2022-01-20 21:33 UTC, matthewmcnew commented on synced-secrets.html.md.erb
> +To start synchronizing a secret to all namespaces with builds, use `kubectl` to create a docker-registry (Dockercfg or DockerConfigJson) secret in the `build-service` namespace with the following lab
+1

2022-01-20 21:33 UTC, matthewmcnew commented on synced-secrets.html.md.erb
> +<p class='note'><strong>Note:</strong> As of TBS version 1.4 all secrets with the label "tbs-builder-secret-gen-placeholder-secret" will be deleted as this method of secret-syncing is deprecated. Ple
Should this just be in the release notes?

2022-01-20 21:35 UTC, matthewmcnew commented
Should this be updated to be "Using SecretGen controller Secrets to use private cluster builders?" (So, to reframe it as less of a TBS feature and more how we are making it possible to use SecretgenController?)

2022-01-24 16:05 UTC, tylerphelan commented on synced-secrets.html.md.erb
> +To start synchronizing a secret to all namespaces with builds, first create the secret in the secret-gen-controller namespace ("build-service") using the `kubectl` cli.
maybe just `To start synchronizing a secret to all namespaces with builds, first create the secret in the `build-service` namespace using the `kubectl` cli.

2022-01-24 16:07 UTC, tylerphelan commented on synced-secrets.html.md.erb
> +  toNamespace: desired-export-namespace
maybe do "*" here to do all build namespaces

2022-01-24 16:08 UTC, tylerphelan commented on synced-secrets.html.md.erb
> +To stop synchronizing a secret, delete the secret from the `build-service` namespace or remove the corresonding secret-export resource from the secret located in the `build-service` namespace.
`secret-export` -> `SecretExport` maybe

2022-01-24 16:10 UTC, tylerphelan requested changes
very nice

2022-01-24 20:23 UTC, tylerphelan approved these changes

2022-01-25 16:05 UTC, merged