Added legacy SBOM deprecation notice.
pivotal-cf/docs-build-service pull request #307
Opened 2022-09-15 17:27 UTC by ncarlson

https://github.com/pivotal/build-service/issues/882

2022-09-15 17:55 UTC, tomkennedy513 approved these changes

2022-09-15 18:15 UTC, tylerphelan commented on getting-started.html.md.erb
> +Older (legacy) SBOM formats are deprecated and are disabled by default in TBS. Support for legacy SBOM formats be
maybe remove s from the legacy bom as the "s" implies the new bom.

`Older (legacy) SBOM formats are deprecated and are disabled by default in TBS. Support for legacy SBOM formats be` -> `The (legacy) CNB BOM format is deprecated and disabled by default in TBS. Support for legacy BOM can be`

2022-09-15 18:17 UTC, tomkennedy513 requested changes

2022-09-15 18:17 UTC, tomkennedy513 commented on installing-no-kapp.html.md.erb
> +Older (legacy) SBOM formats are deprecated and are disabled by default in TBS. Support for legacy SBOM formats be
Enabled by default

2022-09-15 18:30 UTC, matthewmcnew commented on getting-started.html.md.erb
> +[Buildpacks API 0.7.0](https://buildpacks.io/docs/reference/spec/migration/buildpack-api-0.6-0.7/#new-standardized-sbom-format).
The buildpacks api is really intended for buildpack authors not users of TBS. Perhaps, linking to https://buildpacks.io/docs/tools/pack/cli/pack_sbom_download/ would be more appropriate?

2022-09-16 20:09 UTC, ncarlson commented on getting-started.html.md.erb
> +[Buildpacks API 0.7.0](https://buildpacks.io/docs/reference/spec/migration/buildpack-api-0.6-0.7/#new-standardized-sbom-format).
I've removed the mention of buildpacks, as it does seem out of place.

2022-09-16 20:16 UTC, tylerphelan commented on managing-images.html.md.erb
>  The kp cli allows you to view the bill of materials in an image built by a Build.
>The kp cli allows you to view the bill of materials in an image built by a Build.
we should mention this is no longer supported in kp 0.7.0+

2022-09-16 20:16 UTC, tylerphelan approved these changes

2022-09-16 21:08 UTC, ncarlson commented on getting-started.html.md.erb
> +Older (legacy) SBOM formats are deprecated and are disabled by default in TBS. Support for legacy SBOM formats be
Thanks, @tylerphelan. I reverted this PR and opened a new draft PR with your suggestions. Found here: https://github.com/pivotal/docs-tap/pull/1570

2022-09-16 21:09 UTC, ncarlson commented on installing-no-kapp.html.md.erb
> +Older (legacy) SBOM formats are deprecated and are disabled by default in TBS. Support for legacy SBOM formats be
Thanks, @tomkennedy513.  I reverted this PR and opened a new draft PR with your suggestions. Found here: https://github.com/pivotal/docs-tap/pull/1570

2022-09-16 21:10 UTC, ncarlson commented on getting-started.html.md.erb
> +[Buildpacks API 0.7.0](https://buildpacks.io/docs/reference/spec/migration/buildpack-api-0.6-0.7/#new-standardized-sbom-format).
Thanks, @matthewmcnew. I reverted this PR and opened a new draft PR here: https://github.com/pivotal/docs-tap/pull/1570.

2022-09-19 21:18 UTC, merged

2022-09-20 14:44 UTC, ncarlson commented on managing-images.html.md.erb
>  The kp cli allows you to view the bill of materials in an image built by a Build.
Thank you. Added it.